---
# Null task to hack around bug #14655
- hosts: www
- hosts: pg
- hosts: solr

- hosts: pg
  become: yes
  pre_tasks:
      - name: overriding version details
        set_fact:
          ansible_distribution_major_version: "6"
          when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"

      - name: install dependencies
        yum: pkg={{item}} state=installed enablerepo=epel
        with_items:
            - python27-psycopg2
        when: "ansible_os_family == 'RedHat'"
  roles:
      - ANXS.postgresql

- hosts: solr
  become: yes
  roles:
      - role: geerlingguy.java
        when: "ansible_os_family == 'RedHat'"
        java_packages:
            - java-1.8.0-openjdk
      - geerlingguy.solr
  tasks:
      - name: install dependencies
        yum: pkg={{item}} state=installed
        with_items:
            - git-core
        when: "ansible_os_family == 'RedHat'"

      # latest versions of CentOS (RHEL?) are shipped with python-toolsets 0.9.8
      - name: upgrade to latest version of toolsets
        pip:
            name: setuptools
            extra_args: --upgrade
        when: "ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'"

      - name: creating temporary working directory
        tempfile:
            state: directory
            suffix: ckan
        register: ckan_tmpdir

      - name: getting ckan
        git:
            repo: "{{ ckan_repo }}"
            version: "{{ ckan_branch }}"
            dest: "{{ ckan_tmpdir.path }}"
            depth: 1
            force: true

      - name: stopping solr
        service:
            name: solr
            state: stopped

      - name: updating solr schema
        copy:
            src: "{{ ckan_tmpdir.path }}/ckan/config/solr/{{ ckan_schema }}"
            dest: "/var/solr/data/ckan/conf/schema.xml"
            owner: "{{ solr_user }}"
            remote_src: true

      - name: removing managed schema
        file:
            path: "/var/solr/data/ckan/conf/managed-schema"
            state: absent

      - name: starting solr
        service:
            name: solr
            state: started


- hosts: www
  become: yes
  environment:
      PATH: /usr/local/bin:{{ ansible_env.PATH }}

  roles:
      - geerlingguy.nginx

  tasks:
      - name: enable epel repository
        yum:
            pkg: epel-release
            state: installed
        when: "ansible_os_family == 'RedHat'"

      - name: install core dependencies pt.1
        yum: pkg={{item}} state=installed
        with_items:
            - git-core
            - postgresql-devel
            - python2
            - python-pip
            - python-virtualenv
            - zlib-devel
            - libjpeg-devel
            - "@Development tools"
        when: "ansible_os_family == 'RedHat'"

      # RedHat/CentOS sepcific
      - name: install core dependencies pt.2
        yum: pkg={{item}} state=installed
        with_items:
            - redis
        when: "ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'"

      # Amazon linux specific
      - name: install core dependencies pt.2
        yum: pkg={{item}} state=installed enablerepo=epel
        with_items:
            - redis
        when: "ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'"

      - name: ensuring home exists
        file:
            path: "{{ ckan_checkout_root }}"
            state: directory
            owner: "nginx"
            group: "nginx"
            recurse: yes

      - name: ensuring socket dir exists
        file:
            path: "{{ ckan_socket_path }}"
            state: directory
            owner: "nginx"
            group: "nginx"
            recurse: yes

      - name: getting ckan
        git:
            repo: "{{ ckan_repo }}"
            version: "{{ ckan_branch }}"
            dest: "{{ ckan_checkout_root }}/ckan"
            force: true
            depth: 1

      # We really want to use the platform-provided psycopg instead of the
      # we'd get through pip.
      - name: remove platform-provided dependencies
        lineinfile:
            path: "{{ ckan_checkout_root }}/ckan/{{ item }}"
            state: absent
            regexp: "psycopg2"
        with_items: "{{ ckan_dependency_files }}"

      - name: install ckan dependencies
        pip:
            requirements: "{{ item }}"
            chdir: "{{ ckan_checkout_root }}/ckan"
        with_items: "{{ ckan_dependency_files }}"

      - name: install ckan
        pip:
            name: "."
            editable: true
            chdir: "{{ ckan_checkout_root }}/ckan"

      - name: checking CKAN config file exists
        stat:
            path: "{{ ckan_checkout_root }}/ckan/production.ini"
        register: ckan_config

      - name: creating missing CKAN config file
        command: "paster make-config ckan {{ ckan_checkout_root }}/ckan/production.ini"
        args:
            chdir: "{{ ckan_checkout_root }}/ckan"
        when: ckan_config.stat.exists == False

      - name: updating CKAN config file - db
        lineinfile:
            path: '{{ ckan_checkout_root }}/ckan/production.ini'
            regexp: '^sqlalchemy\.url'
            line:  'sqlalchemy.url = postgresql://ckan:{{ vault_pg_ckan_pass }}@{{ db_host }}/ckan'

      - name: updating CKAN config file - solr
        lineinfile:
            path: '{{ ckan_checkout_root }}/ckan/production.ini'
            regexp: '^#solr_url'
            line:  'solr_url = http://{{ solr_url }}/solr/ckan'
